# Generated by Django 3.1.13 on 2021-12-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('shortcut', models.CharField(max_length=3, verbose_name='ISO 3166-α2')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Country')),
                ('shortcut', models.CharField(max_length=6, verbose_name='ISO 3166-2')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'unique_together': {('country', 'shortcut')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('hn', models.CharField(max_length=15, verbose_name='House number')),
                ('zipcode', models.CharField(max_length=5, verbose_name='Zipcode')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state', verbose_name='State')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'unique_together': {('street', 'hn', 'zipcode')},
            },
        ),
    ]
