# Generated by Django 3.1.13 on 2021-12-02 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('ceiling_height', models.FloatField(blank=True, null=True, verbose_name='Ceiling height')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Bathrooms')),
                ('garage', models.IntegerField(default=0, verbose_name='Garage')),
                ('sqft', models.FloatField(verbose_name='m²')),
                ('lot_size', models.FloatField(verbose_name='Lot size')),
                ('image', models.ImageField(upload_to=listings.models.listing_dir_path, verbose_name='Image')),
                ('listing_for', models.CharField(choices=[('R', 'Rent'), ('S', 'Sell')], default='S', max_length=5, verbose_name='Listing for')),
                ('protected', models.BooleanField(default=False, verbose_name='Monument Protected')),
                ('is_published', models.BooleanField(default=True, verbose_name='Online')),
                ('free_from', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Free from')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('address', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingToCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=listings.models.listing_dir_path, verbose_name='Image')),
                ('short_description', models.CharField(max_length=255, verbose_name='Short description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.listing', verbose_name='Listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listings.listingtype', verbose_name='Listing type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.realtor', verbose_name='Realtor'),
        ),
    ]
